# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producttypename', models.CharField(max_length=100)),
            ],
        ),
    ]
