# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentTypeAccountNumber', models.IntegerField()),
                ('paymentTypeName', models.CharField(max_length=50)),
            ],
        ),
    ]
