# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=100)),
                ('departmentBudget', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='paymenttypeid',
        ),
    ]
