# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computerPurchaseDate', models.CharField(max_length=50)),
                ('computerDecomissionDate', models.CharField(max_length=50)),
            ],
        ),
    ]
