# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeetype'),
        ('api', '0002_customerpaymenttype'),
    ]

    operations = [
    ]
