# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20170424_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerFirstName', models.CharField(max_length=100)),
                ('customerLastName', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('customerSince', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerPaymentType',
        ),
    ]
