# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_computertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.CharField(max_length=25)),
                ('productDescription', models.CharField(max_length=100)),
            ],
        ),
    ]
